import './globals.css'
import { Inter } from 'next/font/google'
import  AppWrapper  from './context/AppContext';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: ' Interview Buddy',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AppWrapper>
      <body className={inter.className}>
        {children}
      </body>
      </AppWrapper>
    </html>
  )
}
